on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  
      - name: test
        uses: PenguinCabinet/tyranoscript-packager-action@v0.1.14
        with:
          workingdirectory: "test"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: $(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")